### ISSUE TITLE
QbasicTimer : stop : Failed. Possibly trying to stop from a different thread 

### ISSUE THREAD

**Issue by vmarar** [KristapsE/DP4-AI#49] opened 2021-03-10 14:03 UTC
`QbasicTimer : stop : Failed. Possibly trying to stop from a different thread `

I keep getting this error and the GUI quits automatically. It does not give me a traceback 

Thanks!

**Comment by KristapsE** [comment] 2021-03-10 19:29
This sounds like a GUI issue - @HowarthA wrote pretty much all of it, so hopefully he might be able to look into this. In the meantime, could you please let us know your OS and what versions of Python and PyQT are you running?

**Comment by vmarar** [comment] 2021-03-10 22:29
It is version 5.15.1

**Comment by HowarthA** [comment] 2021-03-11 15:46
Hi, the problem here is likely PyDP4 starts running on a new thread and reaches a problem with the inputs and hence attempts to quit. Could you give us some details about your input files? Are you running DP4-AI with pre-completed calculations or are you using the GUI to launch the calculations for you, if so, how far through the calculations has the program reached prior to quitting?

**Comment by vmarar** [comment] 2021-03-11 16:09
Almost nothing has been calculated, I would say a couple seconds before exiting.

 I think this may be a larger issue because I ran the program using the command line and conformer energies are not being generated in the .tout file, I get a tout file that says " Enter Cartesian file name :      " and nothing else. 

Do you think this is an issue with my input ?

**Comment by vmarar** [comment] 2021-03-15 14:40
It seems to quit immediately. I switched over to the command line version because batch processing is more important to me and came across another issue. All of my .tout files generated have empty lines that say Enter Cartesian Coordinate File Name

**Comment by HowarthA** [comment] 2021-03-15 15:12
Hi, it seems as though this is probably related to a known bug in TINKER, have a look at this issue here #48

**Comment by vmarar** [comment] 2021-03-15 15:41
Getting to that error also required me changing line 60 in Tinker.py as I kept getting errors that key files were not being found(or created) for each of the diastereomers files. 

my file structure is as follows: 
- DP4-AI
     - packages 
         - NMR Data 
               -test 
                         -proton
               -output 
                          -out.sdf
                          -sdftinkerxyz
                          -default.key
         - tinker 

The error I get without changing line 60 is : No such file or directory ./out1.key

**Comment by HowarthA** [comment] 2021-03-15 16:00
also have you changed the TINKER path on line 60 of PyDP4.py?

**Comment by vmarar** [comment] 2021-03-15 16:04
yes that has been changed

**Comment by KristapsE** [comment] 2021-03-15 16:53
Have you applied the fix from #36 ? It addresses the new TINKER command line interface which requires interactive input - this wasn't the case when DP4-AI was released.

**Comment by vmarar** [comment] 2021-03-15 17:23
I changed that now and it shows no change, it still isn't generating key files for diastereomers files. I looked in the Tinker.py file but can't seem to find where it creates those key files. Before I changed it so it was reading from the same key file for each diastereomers but I assume that is incorrect

**Comment by vmarar** [comment] 2021-03-16 15:13
I found the main issue, sdf2tinkerxyz keeps creating a file in the main folder with the entire path as the name, I was able to change the code so It creates the key and xyz folder in my output folder but it seems to still use the entire path as the name. Would you know how/where to change it so it creates files using out1, out2, out3 etc key and xyz files? I couldn't find any useful information on their site

**Comment by KristapsE** [comment] 2021-03-16 15:42
I have a feeling you might be using the tool slightly differently from what how it was intended. Have you had a look at the original data (https://www.repository.cam.ac.uk/handle/1810/303052) to see what a job folder generally looks like? Before DP4-AI has been run, the job folder should just contain the sdf of one or more diastereomers.

From command line running a job would then be by cd-ing in the job folder and then running

/path/to/PyDP4.py Candidate CandidateNMR

if using diastereomer generation or

/path/to/PyDP4.py Candidate1 Candidate2 ... CandidateN CandidateNMR

if not using diastereomer generation.

I would probably at this point suggest starting from a fresh copy of DP4-AI and just applying the fix from #36, but no other modifications.

Hope this helps.

**Comment by KristapsE** [comment] 2021-03-16 15:57
Also I just thought I'd also remind that the preferred way of letting DP4-AI know where to find DFT and MM software packages is through settings.cfg. There is a settings.example file in the official package, please modify this to match your installations and rename it to settings.cfg. No other software path-related modifications to Python code should be necessary.

**Comment by vmarar** [comment] 2021-03-17 14:19
Thank you so much! That worked! Also would you know what 'Invalid MIT-MAGIC COOKIE-1 key' signifies or its just an error that I can ignore ?

**Comment by KristapsE** [comment] 2021-03-17 18:39
About an hour of computational time for 1 conformer seems reasonable. The times shown in the paper are the NMR processing times excluding molecular mechanics and DFT calculation time. DP4-AI innovation is that it removes the need to analyze the NMR spectrum and manually extract and assign peaks to the atoms in the molecules - which is actually very human intensive, therefore that manual intepretation part sees the dramatic speedup.

I'm glad the issue has been solved - I will close the issue now.

**Closed by KristapsE** 2021-03-17 18:39 UTC
